version: '3'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kishor@2210
      POSTGRES_DB: school
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kishor@2210
      POSTGRES_DB: school
    ports:
      - "5433:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:    

